import type { Lesson, Track } from "./types";

export const tracks: Track[] = [
  { id: "ai-engineering", title: "AI Engineering" },
  { id: "frontend", title: "Frontend Engineering" },
  { id: "backend", title: "Backend Engineering" },
  { id: "system-design", title: "System Design" },
];

export const lessons: Lesson[] = [
  {
    id: "prompt-engineering",
    title: "Prompt Engineering",
    description:
      "Design reliable prompts for production LLM features — structure, few-shot, chain-of-thought, and guardrails.",
    difficulty: "intermediate",
    estimatedMinutes: 45,
    objectives: [
      "Structure prompts with role, task, constraints, and output format",
      "Apply few-shot and chain-of-thought techniques",
      "Version and evaluate prompts before deployment",
    ],
    prerequisites: ["Basic familiarity with chat APIs"],
    concepts: [
      "System vs user vs assistant messages",
      "Few-shot prompting",
      "Chain-of-thought",
      "Temperature and top-p",
      "Output format constraints",
      "Prompt versioning",
    ],
    productionTopics: [
      "A/B testing prompts in production",
      "Structured output validation",
      "Cost control with max_tokens",
      "Logging prompts for regression analysis",
    ],
    interviewFocus: [
      "Prompt design tradeoffs",
      "When to fine-tune vs prompt",
      "Preventing prompt injection",
      "JSON output reliability",
    ],
    tags: ["llm", "prompts", "ai-engineering"],
    recommendedResources: ["OpenAI prompt engineering guide"],
  },
  {
    id: "rag",
    title: "Retrieval Augmented Generation",
    description:
      "Ground LLM responses in private data via chunking, embedding, retrieval, and citation.",
    difficulty: "intermediate",
    estimatedMinutes: 60,
    objectives: [
      "Design ingest → chunk → embed → retrieve → generate pipelines",
      "Choose chunking and retrieval strategies for document types",
      "Evaluate retrieval quality and reduce hallucination",
    ],
    prerequisites: ["Embeddings basics", "Vector search concepts"],
    concepts: [
      "Chunking strategies",
      "Embedding models",
      "Cosine similarity retrieval",
      "Top-k retrieval",
      "Reranking",
      "Citation and grounding",
    ],
    productionTopics: [
      "Stale index handling",
      "Multi-tenant document isolation",
      "Retrieval logging for debugging",
      "Hybrid keyword + vector search",
    ],
    interviewFocus: [
      "RAG vs fine-tuning",
      "Chunk size tradeoffs",
      "Failure modes when retrieval is wrong",
      "Evaluating RAG quality",
    ],
    tags: ["rag", "embeddings", "ai-engineering"],
  },
  {
    id: "embeddings",
    title: "Embeddings & Vector Search",
    description:
      "Semantic search with embedding models, similarity metrics, and vector indexes.",
    difficulty: "intermediate",
    estimatedMinutes: 40,
    objectives: [
      "Explain how embeddings enable semantic retrieval",
      "Compare cosine similarity vs dot product",
      "Plan re-indexing when switching embedding models",
    ],
    prerequisites: ["Basic linear algebra intuition"],
    concepts: [
      "Dense vector representations",
      "Cosine similarity",
      "Asymmetric embeddings (query vs document)",
      "Dimensionality tradeoffs",
      "ANN indexes (HNSW, IVF)",
    ],
    productionTopics: [
      "Batch embedding pipelines",
      "Embedding model versioning",
      "pgvector vs dedicated vector DBs",
      "Recall@k benchmarking",
    ],
    interviewFocus: [
      "Why not mix embedding models",
      "HNSW vs IVFFlat",
      "Semantic vs keyword search",
    ],
    tags: ["embeddings", "vector-db", "ai-engineering"],
  },
  {
    id: "ai-agents",
    title: "AI Agents & Tool Use",
    description:
      "Autonomous loops with tool calling, planning, memory, and production guardrails.",
    difficulty: "advanced",
    estimatedMinutes: 55,
    objectives: [
      "Implement observe → plan → act agent loops",
      "Define tool schemas and validate execution safely",
      "Set iteration limits and human-in-the-loop checkpoints",
    ],
    prerequisites: ["Function calling", "Prompt engineering"],
    concepts: [
      "ReAct pattern",
      "Tool schemas and execution",
      "Agent memory (short vs long term)",
      "Multi-agent orchestration",
      "Iteration limits",
    ],
    productionTopics: [
      "Sandboxed tool execution",
      "Audit logging every tool call",
      "Cost caps per agent run",
      "Human approval for high-stakes actions",
    ],
    interviewFocus: [
      "Agent vs chatbot with tools",
      "Preventing infinite loops",
      "Single vs multi-agent architecture",
    ],
    tags: ["agents", "tools", "ai-engineering"],
  },
  {
    id: "react-fundamentals",
    title: "React Fundamentals",
    description:
      "Components, state, hooks, and rendering — the foundation of modern UI engineering.",
    difficulty: "beginner",
    estimatedMinutes: 50,
    objectives: [
      "Build components with correct state and prop patterns",
      "Explain reconciliation and when re-renders occur",
      "Compose UI with hooks and compound components",
    ],
    prerequisites: ["JavaScript ES6+", "HTML/CSS"],
    concepts: [
      "Components and JSX",
      "Props vs state",
      "useState and useEffect",
      "Virtual DOM reconciliation",
      "List keys",
      "Composition patterns",
    ],
    productionTopics: [
      "Error boundaries in widget dashboards",
      "Colocating state in large trees",
      "TypeScript prop contracts",
    ],
    interviewFocus: [
      "What triggers re-renders",
      "Props vs state",
      "Why keys matter in lists",
      "Hooks rules",
    ],
    tags: ["react", "frontend"],
  },
  {
    id: "nextjs-app-router",
    title: "Next.js App Router",
    description:
      "Server Components, layouts, streaming, and server/client boundaries in Next.js.",
    difficulty: "intermediate",
    estimatedMinutes: 55,
    objectives: [
      "Choose Server vs Client Components appropriately",
      "Structure routes with nested layouts and loading states",
      "Implement Server Actions for mutations",
    ],
    prerequisites: ["React fundamentals"],
    concepts: [
      "Server Components",
      "Client boundaries ('use client')",
      "Nested layouts",
      "Server Actions",
      "Streaming with Suspense",
      "Route handlers and middleware",
    ],
    productionTopics: [
      "Minimizing client JS bundles",
      "Cache and revalidation policies",
      "Dynamic imports for client-only libs",
    ],
    interviewFocus: [
      "When to use 'use client'",
      "Server Actions vs API routes",
      "Streaming SSR benefits",
    ],
    tags: ["nextjs", "react", "frontend"],
  },
  {
    id: "tanstack-query",
    title: "TanStack Query",
    description:
      "Server state caching, mutations, optimistic updates, and cache invalidation patterns.",
    difficulty: "intermediate",
    estimatedMinutes: 40,
    objectives: [
      "Design hierarchical query key factories",
      "Implement optimistic updates with rollback",
      "Configure staleTime and invalidation per data type",
    ],
    prerequisites: ["React hooks", "REST APIs"],
    concepts: [
      "Query keys and cache entries",
      "staleTime vs gcTime",
      "Mutations and invalidation",
      "Optimistic updates",
      "Infinite queries",
      "Prefetching",
    ],
    productionTopics: [
      "Centralized query key factories",
      "Global error handlers",
      "Avoiding duplicate fetches",
    ],
    interviewFocus: [
      "TanStack Query vs Redux for API data",
      "staleTime vs gcTime",
      "Optimistic update rollback",
    ],
    tags: ["react", "data-fetching", "frontend"],
  },
  {
    id: "react-performance",
    title: "React Performance",
    description:
      "Profiling, memoization, virtualization, and concurrent features for fast UIs.",
    difficulty: "intermediate",
    estimatedMinutes: 45,
    objectives: [
      "Profile components with React DevTools",
      "Apply virtualization for long lists",
      "Use useTransition for non-urgent updates",
    ],
    prerequisites: ["React fundamentals"],
    concepts: [
      "React.memo",
      "useMemo",
      "useCallback",
      "Virtual DOM and reconciliation",
      "Rendering lifecycle",
      "useTransition and useDeferredValue",
    ],
    productionTopics: [
      "Dashboard optimization",
      "Large data tables",
      "Infinite scrolling lists",
      "Bundle size budgets in CI",
    ],
    interviewFocus: [
      "When React.memo helps vs hurts",
      "Virtualization for 10k rows",
      "useTransition vs debouncing",
      "Profiling workflow",
    ],
    tags: ["react", "performance", "frontend"],
  },
  {
    id: "rest-api-design",
    title: "REST API Design",
    description:
      "Resource-oriented APIs, HTTP semantics, versioning, pagination, and error contracts.",
    difficulty: "intermediate",
    estimatedMinutes: 45,
    objectives: [
      "Design predictable URL and status code conventions",
      "Document APIs with OpenAPI",
      "Implement cursor pagination and idempotent mutations",
    ],
    prerequisites: ["HTTP basics"],
    concepts: [
      "Resource-oriented URLs",
      "HTTP methods and status codes",
      "Pagination (cursor vs offset)",
      "API versioning",
      "Idempotency keys",
      "Error response shape",
    ],
    productionTopics: [
      "Rate limiting public endpoints",
      "Consistent error contracts",
      "OpenAPI as source of truth",
    ],
    interviewFocus: [
      "PUT vs PATCH",
      "401 vs 403",
      "Idempotent POST design",
      "API versioning strategies",
    ],
    tags: ["api", "backend"],
  },
  {
    id: "authentication",
    title: "Authentication",
    description:
      "Sessions, JWTs, OAuth, and secure credential handling in production systems.",
    difficulty: "intermediate",
    estimatedMinutes: 50,
    objectives: [
      "Compare session cookies vs JWT tradeoffs",
      "Implement secure password hashing and refresh token rotation",
      "Integrate OAuth/OIDC flows",
    ],
    prerequisites: ["REST APIs", "HTTP cookies"],
    concepts: [
      "Password hashing (bcrypt/argon2)",
      "Session cookies vs JWTs",
      "Refresh token rotation",
      "OAuth 2.0 authorization code flow",
      "MFA basics",
    ],
    productionTopics: [
      "httpOnly secure cookies",
      "Login rate limiting",
      "Auth event audit logs",
      "Token revocation strategies",
    ],
    interviewFocus: [
      "JWT storage: cookie vs localStorage",
      "How to revoke JWTs",
      "OAuth flow walkthrough",
      "Session vs token architecture",
    ],
    tags: ["auth", "security", "backend"],
  },
  {
    id: "postgresql",
    title: "PostgreSQL",
    description:
      "Schema design, indexing, query optimization, migrations, and scaling reads.",
    difficulty: "intermediate",
    estimatedMinutes: 50,
    objectives: [
      "Design schemas and indexes for query patterns",
      "Use EXPLAIN ANALYZE to diagnose slow queries",
      "Run safe migrations with connection pooling",
    ],
    prerequisites: ["SQL basics"],
    concepts: [
      "Normalization vs denormalization",
      "B-tree and GIN indexes",
      "EXPLAIN ANALYZE",
      "Transactions and isolation",
      "Connection pooling",
      "Read replicas",
    ],
    productionTopics: [
      "Migration rollback plans",
      "Slow query monitoring",
      "PITR backups",
      "PgBouncer for serverless",
    ],
    interviewFocus: [
      "When indexes hurt writes",
      "ACID properties",
      "Replication lag issues",
      "Choosing shard keys",
    ],
    tags: ["database", "backend"],
  },
  {
    id: "system-design-fundamentals",
    title: "System Design Fundamentals",
    description:
      "Scaling patterns, CAP tradeoffs, load balancing, caching, and reliability basics.",
    difficulty: "advanced",
    estimatedMinutes: 60,
    objectives: [
      "Explain horizontal vs vertical scaling tradeoffs",
      "Apply caching layers appropriately",
      "Design for failure with timeouts and circuit breakers",
    ],
    prerequisites: ["Backend fundamentals", "Networking basics"],
    concepts: [
      "Horizontal vs vertical scaling",
      "Load balancing (L4 vs L7)",
      "Caching layers",
      "CAP theorem",
      "Circuit breakers",
      "Message queues",
    ],
    productionTopics: [
      "Graceful degradation",
      "Health checks and failover",
      "CDN for static assets",
      "Multi-region routing",
    ],
    interviewFocus: [
      "Design a URL shortener",
      "Read vs write scaling",
      "Cache stampede prevention",
      "When to shard a database",
    ],
    tags: ["system-design", "architecture"],
  },
  {
    id: "observability",
    title: "Observability",
    description:
      "Logs, metrics, traces, SLOs, and alerting for production systems.",
    difficulty: "intermediate",
    estimatedMinutes: 40,
    objectives: [
      "Define SLIs and SLOs for critical user journeys",
      "Implement structured logging with correlation IDs",
      "Design alerts that reduce noise while catching real issues",
    ],
    prerequisites: ["Production deployment experience"],
    concepts: [
      "Logs, metrics, traces",
      "SLI / SLO / SLA",
      "Error budgets",
      "Distributed tracing",
      "Correlation IDs",
      "RED method (rate, errors, duration)",
    ],
    productionTopics: [
      "Structured JSON logging",
      "Alert runbooks",
      "SLO burn rate alerts",
      "OpenTelemetry adoption",
    ],
    interviewFocus: [
      "SLI vs SLO vs SLA",
      "Key API metrics",
      "Reducing alert fatigue",
      "Debugging with traces",
    ],
    tags: ["observability", "sre", "system-design"],
  },
];
